version: '3'
services:
  servidor1:
    container_name: servidor1
    build: 
      context: ./servidor1
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - MYSQL_HOST=maestro1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_Db=db_informacion
      - MYSQL_PORT=3306
    depends_on:
      - maestro1

  servidor2:
    container_name: servidor2
    build: 
      context: ./servidor2
      dockerfile: Dockerfile
    ports:
      - 5002:5000
    environment:
      - MYSQL_HOST=maestro2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_Db=db_informacion
      - MYSQL_PORT=3306
    depends_on:
      - maestro2

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: "maestro1,maestro2"
      PMA_ARBITRARY: 1
    ports:
      - 8081:80

  maestro1:
    image: mysql:8.0
    container_name: maestro1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    ports:
      - 3306:3306
    volumes:
      - maestro1_data:/var/lib/mysql
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=db_informacion --gtid-mode=ON --enforce-gtid-consistency=ON --log-slave-updates=ON --skip-host-cache --skip-name-resolve

  maestro2:
    image: mysql:8.0
    container_name: maestro2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    ports:
      - 3307:3306  
    volumes:
      - maestro2_data:/var/lib/mysql
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=db_informacion --gtid-mode=ON --enforce-gtid-consistency=ON --log-slave-updates=ON --skip-host-cache --skip-name-resolve

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - servidor1
      - servidor2

volumes:
  maestro1_data:
  maestro2_data: